name: bootcamp-azure-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  # Core data science
  - pandas=1.5.2
  - numpy=1.23.5
  - scikit-learn=1.1.3
  - matplotlib=3.6.2
  - seaborn=0.12.1
  - jupyter=1.0.0
  - joblib=1.2.0
  - pip:
    # ML specific
    - xgboost==1.7.3
    - mlflow==2.0.1
    - shap==0.41.0
    - optuna==3.0.5
    - plotly==5.11.0
    
    # Azure ML
    - azureml-core==1.47.0
    - azureml-mlflow==1.47.0
    - azureml-dataset-runtime==1.47.0
    - azure-identity==1.12.0
    - azure-keyvault-secrets==4.6.0
    
    # Testing and development
    - pytest==7.2.0
    - pytest-cov==4.0.0
    - pytest-xdist==3.1.0
    - pytest-benchmark==4.0.0
    - black==22.12.0
    - flake8==6.0.0
    - isort==5.11.4
    - safety==2.3.4
    - bandit==1.7.4
    
    # Utilities
    - python-dotenv==0.21.0
    - click==8.1.3
    - tqdm==4.64.1
    - flask==2.2.2
    - gunicorn==20.1.0
